// Added by IMI
const DELETE_ADDRESS_URL = "https://data.moappetit.com/v1/query";

// Function to call the API that adds the address to the address_table in Hasura (postgres db)
export const deleteAddressAPI = async data => {
  let requestOptions = {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    }
  };
  let body = {
    type: "delete",
    args: {
      table: "address",
      where     : { "id" : { "$eq" : parseInt(data)} },
     
    }
  };
  requestOptions.body = JSON.stringify(body);
  try {
    const respons = await fetch(DELETE_ADDRESS_URL, requestOptions); // returning the response generated by the API
    return respons;
  } catch (e) {
    console.log("Request Failed:" + e);
  }
};
export default deleteAddressAPI;
// END: Added by IMI
