// Added by IMI
const GET_RATING_URL = "https://data.moappetit.com/v1/query";

// Function to call the API that adds the address to the address_table in Hasura (postgres db)
export const getAllProductAPI = async data => {
  let requestOptions = {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    }
  };

  let body = {
    type: "select", //query type is select
    args: {
      table: "rating", //the rating table
      columns: ["*"] // get all the coloumns
    }
  };
  requestOptions.body = JSON.stringify(body); //prepared that body to more friendly object that hasura can read
  try {
    const respons = await fetch(GET_RATING_URL, requestOptions); // returning the response generated by the API
    return respons;
  } catch (e) {
    console.log("Request Failed:" + e);
  }
};
export default getAllProductAPI;
// END: Added by IMI
