import getFullUserAPI from "./getFullUserAPI";

// Added by IMI
const GET_ADDRESS_URL = "https://data.moappetit.com/v1/query";

// Function to call the API that adds the address to the address_table in Hasura (postgres db)
export const getAddressAPI = async (data) => {
    let requestOptions = {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        }
    };


    console.log("Global UserID: "+global.user_id);
    
    console.log("Global hasura_id: "+global.hasura_id);
    //If there is no user ID, get it based on the hasura_id that we know exists
    if(global.user_id == null)
    {
        const passInUserObject = {
            hasura_id: global.hasura_id 
          }
      
          let getFullUserResponse = await getFullUserAPI(passInUserObject);
          const resultResponseGetFullUser = await getFullUserResponse.json();
          global.user_id = resultResponseGetFullUser[0].id;
    }
    console.log("Global UserID: "+global.user_id);
    let body = {  
        type: "select",
        args: {
            table: "address",
            "columns": ["*"],
            "where": {user_id: {_eq: global.user_id}}
        }
    };

    /*Get user ID from Hasura*/
 



    requestOptions.body = JSON.stringify(body);
    console.log("Body: " + requestOptions.body);

    try {
        const respons =  await fetch(GET_ADDRESS_URL, requestOptions); // returning the response generated by the API
        //console.log("What about this? Did this hit?");
        //console.log("Response text: " + response.text());
        //console.log("returning: "+ respons["returning"]);
        
        //console.log(respons);
        return respons;
    } catch (e) {
        console.log('Request Failed:' + e);
    }
};

export default getAddressAPI;

// END: Added by IMI