// Added by IMI
const GET_ADDRESS_URL = "https://data.moappetit.com/v1/query";

// Function to call the API that adds the address to the address_table in Hasura (postgres db)
export const getAddressAPI = async (data) => {
    let requestOptions = {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        }
    };

    let body = {  
        type: "select",
        args: {
            table: "address",
            "columns": ["*"]


        }
    };

    requestOptions.body = JSON.stringify(body);
    console.log("Body: " + requestOptions.body);

    try {
        const respons =  await fetch(GET_ADDRESS_URL, requestOptions); // returning the response generated by the API
        console.log("What about this? Did this hit?");
        //console.log("Response text: " + response.text());
        console.log("returning: "+ respons["returning"]);
        
        console.log(respons);
        return respons;
    } catch (e) {
        console.log('Request Failed:' + e);
    }
};

export default getAddressAPI;

// END: Added by IMI