import React from 'react';
const PASSWORD_URL = "https://auth.moappetit.com/v1/forgot-password";

const passwordAPI = async (data) => {
  let requestOptions = {
    method: "POST",
    headers: {
        "Content-Type": "application/json"
    }
  };

let body = {
    provider: "email",
    data: {
      email: data.email.toLowerCase(),
      password: data.password
    }
  };
requestOptions.body = JSON.stringify(body);

try {
    const response = await fetch(PASSWORD_URL, requestOptions)
    return response; // Returning the response generated by the API
} catch (e) {
  console.log("Request Failed: " + e.message);
}
};

export default passwordAPI;
